	#base	"../../#users/custom/resource/ui/freezepanelkillerhealth.res"
	#base 	"../../_jofrenew/resource/#beta/hp_player.res"
	#base	"../../_stream/resource/ui/freezepanelkillerhealth.res"
	#base	"../../_jofrenew/resource/ui/freezepanelkillerhealth.res"
	#base	"../../_tf2hud/resource/ui/freezepanelkillerhealth.res"