	#base	"../../#users/custom/resource/ui/huditemeffectmeter_engineer.res"
	#base	"../../#users/dane/resource/ui/huditemeffectmeter_engineer.res"
	#base	"../../_stream/resource/ui/huditemeffectmeter_engineer.res"
	#base	"../../_jofrenew/resource/ui/huditemeffectmeter_engineer.res"
	#base	"../../_tf2hud/resource/ui/huditemeffectmeter_engineer.res"