	#base	"../../#users/custom/resource/ui/hudmediccharge.res"
	#base	"../../_stream/resource/ui/hudmediccharge.res"
	#base 	"../../_jofrenew/_customization/resource/ui/hudmediccharge - triuber.res"
	#base 	"../../_jofrenew/_customization/resource/ui/hudmediccharge - style.res"
	#base	"../../_jofrenew/resource/ui/hudmediccharge.res"
	#base	"../../_tf2hud/resource/ui/hudmediccharge.res"