	#base	"../../#users/custom/resource/ui/hudplayerclass.res"
	#base	"../../_stream/resource/ui/hudplayerclass.res"
	#base 	"../../_jofrenew/_customization/resource/ui/hudplayerclass - transparent.res"	
	#base	"../../_jofrenew/resource/ui/hudplayerclass.res"
	#base	"../../_tf2hud/resource/ui/hudplayerclass.res"