	#base	"../../#users/custom/resource/ui/hudtournament.res"
	#base	"../../#users/dane/resource/ui/hudtournament.res"
	#base	"../../_stream/resource/ui/hudtournament.res"
	#base	"../../_jofrenew/resource/ui/hudtournament.res"
	#base	"../../_tf2hud/resource/ui/hudtournament.res"