	#base	"../../#users/custom/resource/ui/lobbycontainerframe_casual.res"
	#base	"../../_stream/resource/ui/lobbycontainerframe_casual.res"
	#base	"../../_jofrenew/resource/ui/lobbycontainerframe_casual.res"
	#base	"../../_jofrenew/_tf2fix/resource/ui/lobbycontainerframe_casual.res"	
//	#base	"../../_tf2hud/resource/ui/lobbycontainerframe_casual.res"