	#base	"../../#users/custom/resource/ui/spectator.res"
	#base	"../../_jofrenew/resource/#beta/spec.res"
	#base	"../../_stream/resource/ui/spectator.res"
	#base	"../../_jofrenew/resource/ui/spectator.res"
	#base	"../../_tf2hud/resource/ui/spectator.res"